alias updt="doas emerge-webrsync ; doas emerge --deep --update --newuse @world"
alias agenda="calcurse"
alias lsl="exa -a --git-ignore -F -1 --color=always"
alias bat="batcat"
alias tree="exa --tree"
alias cls="clear -x"
alias session-kill="pkill -9 -t"
alias rmdir="doas rm -r"
alias inst="doas emerge --ask --newuse --quiet-build" 
alias bc="bc -q"
alias htop="doas htop -t"
alias neo="clear ; neofetch"
alias ne="cd ~ ; node ~/scripts/javaScript/naruto-episode.js"
alias clock="wal -R ; tty-clock -C 4 -c -b"
alias theme="clear ; python ~/github/auto-cursor-change/main.py"
alias wpm="gotta-go-fast -l"
alias arch-speedrun="cd ~/vm ; qemu-img create -f qcow2 Image.img 3G ; time qemu-system-x86_64 -enable-kvm -boot d -drive file=Image.img -m 2G -cdrom ~/Downloads/isos/archlinux-2021.12.01-x86_64.iso -cpu host ; rm Image.img"
alias clip="xclip -selection clipboard"
alias ani-cli="~/download/ani-cli/ani-cli"
alias nvim="xdotool key ctrl+F2 ctrl+equal ; nvim"
alias wallpaper="sh ~/scripts/wallpaper.sh"
alias vim="nvim"
alias todo="vim ~/notes/todo"
alias killy="doas pkill -x ly"
alias pkill="pkill -x"

#One key commands
alias q="clear ; exit"
alias c="clear"
alias h="cd ~"
alias r="wal -R"

#Auto doas
alias reboot="doas reboot"
alias shutdown="doas shutdown"
alias sranger="doas ranger"
alias pacman="doas pacman"

#Git stuff
alias ups="git branch upstream ; git checkout upstream"
alias dps="git checkout main ; git branch --delete upstream ; git pull"
alias commit="git add -A ; git commit -m"
alias clonef="cd ~/download && git clone"
